# Clippy configuration
# https://doc.rust-lang.org/nightly/clippy/lint_configuration.html

allow-private-module-inception = true
avoid-breaking-exported-api = false
disallowed-names = []
disallowed-macros = [
    { path = "std::dbg", reason = "it is okay to use during development, but please do not include it in main branch" },
]
disallowed-methods = [
    { path = "u8::is_ascii_whitespace", reason = "different whitespace definitions" },
    { path = "char::is_ascii_whitespace", reason = "different whitespace definitions" },
    { path = "str::trim_ascii", reason = "different whitespace definitions" },
    { path = "str::trim_ascii_end", reason = "different whitespace definitions" },
    { path = "str::trim_ascii_start", reason = "different whitespace definitions" },
    { path = "str::split_ascii_whitespace", reason = "different whitespace definitions" },
    # TODO: <[u8]> is not working...
    { path = "<[u8]>::trim_ascii", reason = "different whitespace definitions" },
    { path = "<[u8]>::trim_ascii_end", reason = "different whitespace definitions" },
    { path = "<[u8]>::trim_ascii_start", reason = "different whitespace definitions" },
    { path = "<[u8]>::split_ascii_whitespace", reason = "different whitespace definitions" },
]
disallowed-types = [
]
